def addContent(self):
        Black_pawn_1 = Pawn(0, 75, "black")
        Black_pawn_2 = Pawn(75, 75, "black")
        Black_pawn_3 = Pawn(150, 75, "black")
        Black_pawn_4 = Pawn(225, 75, "black")
        Black_pawn_5 = Pawn(300, 75, "black")
        Black_pawn_6 = Pawn(375, 75, "black")
        Black_pawn_7 = Pawn(450, 75, "black")
        Black_pawn_8 = Pawn(525, 75, "black")
        self.scene.addItem(Black_pawn_1)
        self.scene.addItem(Black_pawn_2)
        self.scene.addItem(Black_pawn_3)
        self.scene.addItem(Black_pawn_4)
        self.scene.addItem(Black_pawn_5)
        self.scene.addItem(Black_pawn_6)
        self.scene.addItem(Black_pawn_7)
        self.scene.addItem(Black_pawn_8)
        
        Withe_pawn_1 = Pawn(0, 450, "white")
        White_pawn_2 = Pawn(75, 450, "white")
        White_pawn_3 = Pawn(150, 450, "white")
        White_pawn_4 = Pawn(225, 450, "white")
        White_pawn_5 = Pawn(300, 450, "white")
        White_pawn_6 = Pawn(375, 450, "white")
        White_pawn_7 = Pawn(450, 450, "white")
        White_pawn_8 = Pawn(525, 450, "white")
        self.scene.addItem(Withe_pawn_1)
        self.scene.addItem(White_pawn_2)
        self.scene.addItem(White_pawn_3)
        self.scene.addItem(White_pawn_4)
        self.scene.addItem(White_pawn_5)
        self.scene.addItem(White_pawn_6)
        self.scene.addItem(White_pawn_7)
        self.scene.addItem(White_pawn_8)
        
        White_rook_1 = Rook(0,525,"white")
        White_rook_2 = Rook(525,525,"white")
        self.scene.addItem(White_rook_1)
        self.scene.addItem(White_rook_2)
        
        Black_rook_1 = Rook(0,0,"black")
        Black_rook_2 = Rook(525,0,"black")
        self.scene.addItem(Black_rook_1)
        self.scene.addItem(Black_rook_2)
        
        White_knight_1 = Knight(75,525,"white")
        White_knight_2 = Knight(450,525,"white")
        self.scene.addItem(White_knight_1)
        self.scene.addItem(White_knight_2)
        
        Black_knight_1 = Knight(75,0,"black")
        Black_knight_2 = Knight(450,0,"black")
        self.scene.addItem(Black_knight_1)
        self.scene.addItem(Black_knight_2)
        
        Black_bishop_1 = Bishop(150,0,"black")
        Black_bishop_2 = Bishop(375,0,"black")
        self.scene.addItem(Black_bishop_1)
        self.scene.addItem(Black_bishop_2)


        White_bishop_1 = Bishop(150,525,"white")
        White_bishop_2 = Bishop(375,525,"white")
        self.scene.addItem(White_bishop_1)
        self.scene.addItem(White_bishop_2)
        
        Black_queen = Queen(225,0,"black")
        self.scene.addItem(Black_queen)

        White_queen = Queen(225,525,"white")
        self.scene.addItem(White_queen)
        
        Black_king = King(300,0,"black")
        self.scene.addItem(Black_king)
        
        White_king = King(300,525,"white")
        self.scene.addItem(White_king)